Repository gschool-blue-ocean/admissions-hub-19, pull requests merged in 2023-05, with the labels that each got.

#12 Navbar
  client/src/components/App.jsx
  client/src/components/LoginUI.jsx
  client/src/pages/SignUp.jsx
Labels: enhancement

#14 Navbar
  client/src/pages/SignUp.jsx
Labels: enhancement

#17 new functionality for sign up
  client/src/pages/SignUp.jsx
Labels: enhancement

#20 Navbar
  client/src/components/LoginUI.jsx
  client/src/components/NavBar.jsx
  client/src/pages/Edit_Profile.jsx
Labels: enhancement

#36 Navbar
  client/src/components/AddCohortBtnDashboard.jsx
  client/src/components/CohortShowBtnDashboard.jsx
  client/src/components/DashboardHub.jsx
  client/src/components/ImageCarouselLogin.jsx
  client/src/components/NavBarDashboard.jsx
  client/src/components/ShowCohortBtnDashboard.jsx
  client/src/css/DashboardHub.css
  client/src/pages/Dashboard.jsx
  client/src/pages/Edit_Profile.jsx
  client/src/pages/Login.jsx
  client/src/pages/SignUp.jsx
Labels: enhancement

#41 Navbar
  client/src/components/AddCohortBtnDashboard.jsx
  client/src/components/CohortShowBtnDashboard.jsx
  client/src/components/DashboardHub.jsx
  client/src/components/DeleteCohortBtnDashboard.jsx
  client/src/components/ShowCohortBtnDashboard.jsx
  client/src/components/UILogin.jsx
  client/src/css/DashboardHub.css
  client/src/pages/Login.jsx
Labels: enhancement

#54 Navbar
  client/src/components/DashboardAddCohortBtn.jsx
  client/src/components/DashboardAddStudentBtn.jsx
  client/src/components/DashboardDeleteCohortBtn.jsx
  client/src/components/DashboardHub.jsx
  client/src/components/DashboardNavBar.jsx
  client/src/components/LoginImageCarousel.jsx
  client/src/components/LoginUI.jsx
  client/src/pages/Dashboard.jsx
  client/src/pages/Login.jsx
Labels: bug

#56 Navbar branch
  client/src/components/DashboardAddStudentBtn.jsx
  client/src/css/DashboardHub.css
Labels: enhancement

#57 Readme and related images
  README.md
  client/src/components/InputNotes.jsx
  client/src/css/Interview.css
  documentation/images/Component_Tree.png
  documentation/images/Create_Account.png
  documentation/images/ERD.png
  documentation/images/Login.png
Labels: documentation

#59 Navbar
  client/src/Images/GSymbol.webp
  client/src/Images/GreenLime.jpeg
  client/src/components/DashboardAddStudentBtn.jsx
  client/src/components/InterviewCodingWindow.jsx
  client/src/components/InterviewInputNotes.jsx
  client/src/components/InterviewStarRating.jsx
  client/src/components/InterviewStudentSelector.jsx
  client/src/components/LoginImageCarousel.jsx
  client/src/components/LoginUI.jsx
  client/src/css/LoginUI.module.css
  client/src/pages/Edit_Profile.jsx
  client/src/pages/Interview.jsx
  client/src/pages/Login.jsx
Labels: enhancement

#65 Navbar
  api/src/routesStudents.js
  client/src/components/App.jsx
  client/src/components/DashboardAddCohortBtn.jsx
  client/src/components/DashboardCohortStudentTableBtn.jsx
  client/src/components/DashboardDeleteCohortBtn.jsx
  client/src/pages/Test.jsx
Labels: enhancement

#68 Mel updates
  client/src/components/DashboardCohortStudentTableBtn.jsx
  client/src/components/DashboardHub.jsx
Labels: enhancement

#73 Navbar
  client/src/Images/GreenLime.webp
  client/src/components/DashboardHub.jsx
  client/src/components/DashboardNavBar.jsx
  client/src/components/LoginUI.jsx
  client/src/css/App.module.css
  client/src/css/DashboardHub.css
  client/src/css/LoginUI.module.css
  client/src/pages/SignUp.jsx
Labels: enhancement

#78 Navbar
  client/ClientREADME.md
  client/src/components/App.jsx
  client/src/components/InputNotes.jsx
  client/src/pages/Test.jsx
Labels: documentation
